version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: https://github.com/dapperlabs/prototool
analyze:
  modules:
    - name: github.com/dapperlabs/prototool/cmd/prototool
      type: go
      target: github.com/dapperlabs/prototool/cmd/prototool
      path: cmd/prototool
    - name: github.com/dapperlabs/prototool/internal/cmd/gen-prototool-bash-completion
      type: go
      target: github.com/dapperlabs/prototool/internal/cmd/gen-prototool-bash-completion
      path: internal/cmd/gen-prototool-bash-completion
    - name: github.com/dapperlabs/prototool/internal/cmd/gen-prototool-manpages
      type: go
      target: github.com/dapperlabs/prototool/internal/cmd/gen-prototool-manpages
      path: internal/cmd/gen-prototool-manpages
    - name: github.com/dapperlabs/prototool/internal/cmd/gen-prototool-zsh-completion
      type: go
      target: github.com/dapperlabs/prototool/internal/cmd/gen-prototool-zsh-completion
      path: internal/cmd/gen-prototool-zsh-completion
